language: python
services:
    - docker
before_install:
    - docker-compose -f docker-compose.yml up -d

python:
    - 3.5

before_script:
    - pip install -r tests/requirements.txt

script:
    - python ./tests/container_wait.py
    - pytest